### ISSUE TITLE
Is there a way to auto update the hosts file?

### ISSUE THREAD

**Issue by CHJ85** [cenk/bad-hosts#2]
Hi there. Is there an easy way to update the hosts file in /etc/hosts? Is it even safe?
And how would I go about doing so?`
Also... Your hosts file blocks useful sites such as max.com which is the new HBO Max.

**Comment by cenk** [comment]
> Hi there. Is there an easy way to update the hosts file in /etc/hosts? Is it even safe? And how would I go about doing so?` 

Hi. I'm using pihole for network-wide ad blocking and never tried editing / auto-updating local /etc/hosts file.



> Also... Your hosts file blocks useful sites such as max.com which is the new HBO Max.

Thanks for report. max.com whitelisted.

If you see any other false positives, please let me know.

**Comment by CHJ85** [comment]
Thank you so much.
